version: 0.0
os: linux

files:
  - source: /
    # ec2 목적지
    destination: /home/ec2-user/myapp/lifepost/service
    orverwirte: yes

permissions:
  - object: /home/ec2-user/myapp/lifepost/service
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hook:
  BeforeInstall:
    - location: deploy.sh
      timeout: 300
      runas: root