version: 0.0
os: linux

files:
  - source: /
    # ec2 목적지
    destination: /home/ec2-user/myapp/lifepost/service
    orverwirte: yes

permissions:
  - object: /
    parttern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777

hook:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 30
      runas: ec2-user
#      runas: root