version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/myapp/lifepost/service
permissions:
  - object: /home/ec2-user/myapp/lifepost/service
    parttern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777
hook:
  AfterInstall:
    - location: /home/ec2-user/myapp/lifepost/service/scripts/log.sh
      runas: root
  ApplicationStart:
    - location: /home/ec2-user/myapp/lifepost/service/scripts/deploy.sh
      runas: root
