version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/myapp/lifepost/service
    overwrite: true
file_exists_behavior: OVERWIRTE
permissions:
  - object: /home/ec2-user/myapp/lifepost/service
    parttern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777
hooks:
  ApplicationStart:
    - location: start.sh
      runas: root
