spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://internal.life-post.net:3306/member
      username: member_app
      password: member2023
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        naming:
          physical_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      generate-ddl: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 822708e283cc40a5d5c543e066ad52ec
            client-secret: ZqRqgD8KXju4n1HkV09iVpsXjrosoO5t
            redirect-uri: https://life-post.net/login/oauth2/code/kakao
            authorization_grant_type: authorization_code
            client-authentication-method: client_secret_post
            scope: account_email, profile_image
            cleint-name: Kakao
          google:
            client-id: 946359125310-9dm9pkrfthesqhutjuhr9eq786jkd477.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mustache:
    check-template-location: true
    charset: UTF-8
    servlet:
      content-type: text/html
    enabled: true
    prefix: classpath:/templates/
    suffix: .mustache

jwt:
  secretKey: bGlmZXBvc3QtcHJvZC1qd3Qta2V5LWdlbi0yMDIzMTAxOTEyNDYtY3JlYXRlLWJ5LXdvb2tpbQo=
  access:
    header: Authorization
    expiration: 1800
  refresh:
    header: Authorization-refresh
    expiration: 604800

url: https://life-post.net