#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/member
#    username: member_app
#    password: member2023
#  jpa:
#    hibernate:
#      ddl-auto: create
#      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true