### local properties ###
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;
  jpa:
    hibernate:
      ddl-auto: create
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2