spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_ID}
    password: ${DB_USER_PW}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        naming:
          physical_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization_grant_type: authorization_code
            client-authentication-method: client_secret_post
            scope: account_email, profile_image
            cleint-name: Kakao
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  devtools:
    livereload:
      enabled: true
  mustache:
    check-template-location: true
    charset: UTF-8
    servlet:
      content-type: text/html
    enabled: true
    prefix: classpath:/templates/
    suffix: .mustache
jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    header: Authorization
    expiration: 1800
  refresh:
    header: Authorization-refresh
    expiration: 604800

url: http://localhost:8080