spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev.internal.life-post.net:3306/member
    username: member_app
    password: member2023
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        naming:
          physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: e76259eec862c33998200c0c690bcdba
            client-secret: sfRUgrINtEbg2TTmhDsYOEWtrffsqly8
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization_grant_type: authorization_code
            client-authentication-method: client_secret_post
            scope: account_email, profile_image
            cleint-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  mustache:
    servlet:
      cache: false

jwt:
  secretKey: bcd0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdp
  access:
    header: Authorization
    expiration: 1800
  refresh:
    header: Authorization-refresh
    expiration: 604800