version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: lifepost-member-db
    restart: always
    platform: linux/arm64/v8 # ec2에서는 해당 옵션 지워야함
    volumes:
      - /Users/gimgyeong-u/IdeaProjects/mysqlData:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2023
      MYSQL_DATABASE: member
      MYSQL_USER: member_app
      MYSQL_PASSWORD: member2023
    ports:
      - "3306:3306"
    networks:
      - localnet
#
#  lifepost-service:
#    image: lifepost-service:latest
#    container_name: lifepost-service
#    restart: always
#    ports:
#      - "8080:8080"
#    networks:
#      - localnet

networks:
  localnet: