/* 편지 삽입 */
insert into letter (title, contents, writer, tag, created_date, created_at, updated_at)
values ('test1', 'test1', 'wk', 'TEST', CURDATE() - INTERVAL '14' DAY, now() - INTERVAL '14' DAY,
        now() - INTERVAL '14' DAY),
       ('test2', 'test2', 'wk', 'TEST', CURDATE() - INTERVAL '13' DAY, now() - INTERVAL '13' DAY,
        now() - INTERVAL '13' DAY),
       ('test3', 'test3', 'wk', 'TEST', CURDATE() - INTERVAL '12' DAY, now() - INTERVAL '12' DAY,
        now() - INTERVAL '12' DAY),
       ('test4', 'test4', 'wk', 'TEST', CURDATE() - INTERVAL '11' DAY, now() - INTERVAL '11' DAY,
        now() - INTERVAL '11' DAY),
       ('test5', 'test5', 'wk', 'TEST', CURDATE() - INTERVAL '10' DAY, now() - INTERVAL '10' DAY,
        now() - INTERVAL '10' DAY),
       ('test6', 'test6', 'wk', 'TEST', CURDATE() - INTERVAL '9' DAY, now() - INTERVAL '9' DAY,
        now() - INTERVAL '9' DAY),
       ('test7', 'test7', 'wk', 'TEST', CURDATE() - INTERVAL '8' DAY, now() - INTERVAL '8' DAY,
        now() - INTERVAL '8' DAY),
       ('test8', 'test8', 'wk', 'TEST', CURDATE() - INTERVAL '7' DAY, now() - INTERVAL '7' DAY,
        now() - INTERVAL '7' DAY),
       ('test9', 'test9', 'wk', 'TEST', CURDATE() - INTERVAL '6' DAY, now() - INTERVAL '6' DAY,
        now() - INTERVAL '6' DAY),
       ('test10', 'test10', 'wk', 'TEST', CURDATE() - INTERVAL '5' DAY,
        now() - INTERVAL '5' DAY, now() - INTERVAL '5' DAY),
       ('test11', 'test11', 'wk', 'TEST', CURDATE() - INTERVAL '4' DAY,
        now() - INTERVAL '4' DAY, now() - INTERVAL '4' DAY),
       ('test12', 'test12', 'wk', 'TEST', CURDATE() - INTERVAL '3' DAY,
        now() - INTERVAL '3' DAY, now() - INTERVAL '3' DAY),
       ('test13', 'test13', 'wk', 'TEST', CURDATE() - INTERVAL '2' DAY,
        now() - INTERVAL '2' DAY, now() - INTERVAL '2' DAY),
       ('test14', 'test14', 'wk', 'TEST', CURDATE() - INTERVAL '1' DAY,
        now() - INTERVAL '1' DAY, now() - INTERVAL '1' DAY),
       ('당신은 하루에 <br/>얼마나 깨어 있나요?',
        '일반적인 사람이 하루에 얼마나 의식적으로 살아가는지 아시나요? 의식이 하루를 지배하는 비중은 대략 5%. 나머지 95%는 무의식에 의해 지배됩니다. 즉 대부분의 생각과 행동은 무의식에 의해 지배를 받는다는 것입니다. 그렇기 때문에 우리가 의식적으로 만들고 싶은 습관이나 되고 싶은 모습들을 원하고 노력해도 무의식이 그것을 원하지 않으면 바뀌지 않는다는 것입니다. 그렇기 때문에 우리가 그토록 원하고 변하려 시도해도 바뀌지 않는 것입니다. 그렇다면 우리는 어떡해야 할까요?. 그 해답은 의식에 있습니다. 5%의 의식으로 95%의 무의식을 지배해야 합니다. 방법은 다음과 같습니다. 우리가 무의식적으로 생각하는 것은 사실 의식에 의해 심어진 것들입니다. 가령 출퇴근길에 거칠게 몸을 부딪히는 사람은 매너가 없고 무례한 사람이라고 생각하곤 하죠. 그 사람으로 인해 하루종일 기분이 안좋거나 언짢습니다. 간혹 서로 언쟁을 하거나 몸싸움을 하는등의 일도 일어나죠? 마냥 남일만은 아닙니다. 누구나 한번쯤은 겪어볼만한 일이기도 합니다. 이런 일이 벌어지면 무의식적으로 상대를 비난하거나 몹시 화가납니다. 이렇게 된 이유에는 대중 교통을 이용할 시 서로 몸을 부딪히면 무례하다고 의식적으로 생각했고 의식적으로 상대방을 비난하거나 비판한적이 있었으며 그것이 반복되다 보면 무의식에 새겨지며 이후에는 의식적으로 생각하지 않아도 같은 상황이 벌어지면 무의식에 의해 반복하게 됩니다. 어떻게 그렇게 잘아냐고요? 제가 그랬거든요. 저는 그런 일이 있을 때마다 그렇게 생각하는 저를 의식했고 바꾸고자 했습니다. 의미도 없고 비파괴적인 이 생각을 반복하는 이유는 무엇인가에 대해 생각하고 의식적인 제 생각에 의해 제 무의식은 폭력으로 뒤덮히게 됐습니다. 그래서 저는 이 생각을 의식적으로 바꿔놓아야 했습니다. 어떻게 해야 이 폭력으로 물든 무의식을 선하게 되돌릴 수 있을까요? 폭력적인 생각을 반복했다면, 선한 생각을 반복하면 됩니다. 말은 쉽지만 간단하지 않을겁니다. 의식적으로 선한 생각을 반복해야 하기 떄문입니다. 하지만 반복을 하다보면 어느순간 폭력적인 생각보다 선한 생각을 더 하게되는 경험을 하게 될 것입니다.',
        'wk', 'TEST',
        CURDATE(), now(), now());


