/* 확언 카드 삽입 */
insert into affirmation_card (letter_id, contents, tag, created_at, update_at)
values (1, 'awake anywhere, anytime. :1', null, now() - INTERVAL '14' DAY,
        now() - INTERVAL '14' DAY),
       (2, 'awake anywhere, anytime. :2', null, now() - INTERVAL '13' DAY,
        now() - INTERVAL '13' DAY),
       (3, 'awake anywhere, anytime. :3', null, now() - INTERVAL '12' DAY,
        now() - INTERVAL '12' DAY),
       (4, 'awake anywhere, anytime. :4', null, now() - INTERVAL '11' DAY,
        now() - INTERVAL '11' DAY),
       (5, 'awake anywhere, anytime. :5', null, now() - INTERVAL '10' DAY,
        now() - INTERVAL '10' DAY),
       (6, 'awake anywhere, anytime. :6', null, now() - INTERVAL '9' DAY,
        now() - INTERVAL '9' DAY),
       (7, 'awake anywhere, anytime. :7', null, now() - INTERVAL '8' DAY,
        now() - INTERVAL '8' DAY),
       (8, 'awake anywhere, anytime. :8', null, now() - INTERVAL '7' DAY,
        now() - INTERVAL '7' DAY),
       (9, 'awake anywhere, anytime. :9', null, now() - INTERVAL '6' DAY,
        now() - INTERVAL '6' DAY),
       (10, 'awake anywhere, anytime. :10', null, now() - INTERVAL '5' DAY,
        now() - INTERVAL '5' DAY),
       (11, 'awake anywhere, anytime. :11', null, now() - INTERVAL '4' DAY,
        now() - INTERVAL '4' DAY),
       (12, 'awake anywhere, anytime. :12', null, now() - INTERVAL '3' DAY,
        now() - INTERVAL '3' DAY),
       (13, 'awake anywhere, anytime. :13', null, now() - INTERVAL '2' DAY,
        now() - INTERVAL '2' DAY),
       (14, 'awake anywhere, anytime. :14', null, now() - INTERVAL '1' DAY,
        now() - INTERVAL '1' DAY),
       (15, 'awake anywhere, anytime. :15', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :16', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :17', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :18', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :19', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :20', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :21', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :22', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :23', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :24', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :25', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :26', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :27', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :28', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :29', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :30', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :31', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :32', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :33', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :34', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :35', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :36', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :37', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :38', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :39', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :40', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :41', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :42', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :43', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :44', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :45', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :46', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :47', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :48', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :49', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :50', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :51', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :52', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :53', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :54', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :55', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :56', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :57', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :58', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :59', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :60', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :61', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :62', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :63', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :64', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :65', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :66', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :67', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :68', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :69', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :70', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :71', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :72', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :73', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :74', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :75', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :76', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :77', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :78', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :79', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :80', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :81', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :82', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :83', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :84', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :85', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :86', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :87', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :88', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :89', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :90', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :91', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :92', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :93', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :94', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :95', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :96', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :97', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :98', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :99', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :100', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :101', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :102', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :103', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :104', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :105', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :106', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :107', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :108', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :109', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :110', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :111', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :112', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :113', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :114', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :115', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :116', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :117', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :118', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :119', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :120', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :121', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :122', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :123', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :124', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :125', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :126', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :127', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :128', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :129', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :130', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :131', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :132', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :133', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :134', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :135', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :136', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :137', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :138', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :139', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :140', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :141', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :142', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :143', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :144', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :145', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :146', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :147', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :148', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :149', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :150', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :151', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :152', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :153', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :154', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :155', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :156', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :157', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :158', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :159', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :160', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :161', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :162', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :163', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :164', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :165', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :166', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :167', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :168', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :169', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :170', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :171', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :172', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :173', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :174', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :175', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :176', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :177', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :178', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :179', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :180', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :181', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :182', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :183', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :184', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :185', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY),
       (15, 'awake anywhere, anytime. :186', null, now() - INTERVAL '0' DAY,
        now() - INTERVAL '0' DAY)
;






